add files
strange-square/Game_TP pull request #1
Opened 2020-04-14 07:46 UTC by strange-square

Bogatyreva Daria 921
checkpoint 1

2020-04-14 10:07 UTC, strange-square commented
Я залила проект в срок, но случайно залила сразу в ветку мастера и долго не понимала, как это исправить, чтобы сделать MR. Надеюсь, это не будет считаться сдачей после дедлайна.

2020-04-14 23:08 UTC, alexmikhalevich requested changes

2020-04-14 23:08 UTC, alexmikhalevich commented on test.cpp
> +    Cavalry cav = factory->create_cavalry();
в этой строке в объект присваивается указатель?  
нужно исправить, а потом устранить утечки в тестах

2020-05-03 12:37 UTC, strange-square commented
Я не знала, что вам не приходят уведомления о коммитах

2020-05-06 20:18 UTC, alexmikhalevich approved these changes

2023-02-05 17:14 UTC, merged